'use client';
import { useEffect, useMemo, useState } from 'react';

type Station = { id:string; name:string; area:string; address:string; total:number; bikes:number; docks:number; updatedAt:string; level:'ok'|'warn'|'bad'; label:string; };
type Payload = { city:string; cityName:string; source:string; fetchedAt:string; count:number; summary:{problem:number;noBike:number;noDock:number;ok:number;eBikes:number}; stations:Station[] };


const TOUR_ROUTES = [
 {id:'old-town',name:'老城小吃',theme:'赤崁樓、孔廟、國華街一帶短程移動',tip:'先確認老城核心站點是否有車；熱門時段建議保留步行備案。',stops:[{name:'赤崁樓',keywords:['赤崁樓','民族路','赤崁']},{name:'孔子廟',keywords:['孔子廟','孔廟','南門路']},{name:'國華街',keywords:['國華','海安','中正路']},{name:'臺南美術館',keywords:['美術館','永福','府前路']}]},
 {id:'anping',name:'安平海風',theme:'安平古堡、樹屋、老街與水岸',tip:'安平站點距離較分散，出發前先看還車空位，避免騎到景點附近沒位。',stops:[{name:'安平古堡',keywords:['安平古堡','安平路']},{name:'安平樹屋',keywords:['安平樹屋','古堡街']},{name:'安平老街',keywords:['安平老街','延平街']},{name:'漁光島方向',keywords:['漁光','億載金城','光州路']}]},
 {id:'culture',name:'博物館文化',theme:'美術館、文學館、奇美與校園文化點',tip:'奇美/仁德區距離市中心較遠，適合確認附近有車後作為半日支線。',stops:[{name:'臺南美術館',keywords:['美術館','永福','府前路']},{name:'臺灣文學館',keywords:['文學館','中正路','湯德章']},{name:'臺南大學',keywords:['臺南大學','南大','健康路']},{name:'奇美博物館',keywords:['奇美','仁德','文華路']}]},
 {id:'station-core',name:'車站到市區',theme:'台南車站出發，接老城核心景點',tip:'適合剛到台南先看車站周邊可借數，再往中西區移動。',stops:[{name:'台南車站',keywords:['臺南車站','台南車站','火車站','前站']},{name:'中山公園',keywords:['中山公園','公園路']},{name:'成功大學',keywords:['成功大學','成大','大學路']},{name:'赤崁樓',keywords:['赤崁樓','民族路']}]}]

export default function Page(){
 const [data,setData]=useState<Payload|null>(null); const [err,setErr]=useState('');
 const [q,setQ]=useState(''); const [area,setArea]=useState('全部'); const [mode,setMode]=useState('問題優先'); const [city,setCity]=useState<'taipei'|'tainan'>('tainan');
 useEffect(()=>{let live=true; async function load(){try{setErr(''); const r=await fetch(`/api/youbike?city=${city}`,{cache:'no-store'}); if(!r.ok) throw new Error(String(r.status)); const j=await r.json(); if(live)setData(j)}catch(e){if(live)setErr(String(e))}} load(); const t=setInterval(load,60000); return()=>{live=false; clearInterval(t)}},[city]);
 const areas=useMemo(()=>['全部',...Array.from(new Set((data?.stations||[]).map(s=>s.area))).sort((a,b)=>a.localeCompare(b,'zh-Hant'))],[data]);
 const stations=useMemo(()=>{let xs=(data?.stations||[]).filter(s=>(area==='全部'||s.area===area)&&(`${s.name} ${s.address}`.includes(q))); if(mode==='只看問題') xs=xs.filter(s=>s.level!=='ok'); if(mode==='可借車多') xs=[...xs].sort((a,b)=>b.bikes-a.bikes); if(mode==='可還位多') xs=[...xs].sort((a,b)=>b.docks-a.docks); return xs.slice(0,80)},[data,q,area,mode]);
 const routeCards=useMemo(()=> city==='tainan' ? TOUR_ROUTES.map(route=>({...route,stops:route.stops.map(stop=>({...stop,stations:(data?.stations||[]).filter(s=>stop.keywords.some(k=>`${s.name} ${s.address} ${s.area}`.includes(k))).sort((a,b)=>b.bikes-a.bikes || b.docks-a.docks).slice(0,3)}))})) : [],[city,data]);
 if(err) return <main><div className="error">資料讀取失敗：{err}</div></main>;
 return <main><section className="hero"><div className="eyebrow">Taipei real-time open data lab</div><h1 className="title">台灣 YouBike<br/>即時雷達</h1><p className="subtitle">支援台南 / 台北即時 YouBike 狀態。台南版走 TDX 公共自行車資料，適合做旅遊移動雷達；台北版走免 key 官方 JSON。這是給 MS4 這類快模型測試 agent 產品力的 Vercel 小專案。</p></section>
 {!data?<div className="loading">載入即時站點中…</div>:<><section className="toolbar"><select value={city} onChange={e=>{setCity(e.target.value as 'taipei'|'tainan'); setArea('全部')}}><option value="tainan">台南旅遊雷達</option><option value="taipei">台北通勤雷達</option></select><input placeholder="搜尋站名或地址" value={q} onChange={e=>setQ(e.target.value)}/><select value={area} onChange={e=>setArea(e.target.value)}>{areas.map(a=><option key={a}>{a}</option>)}</select><select value={mode} onChange={e=>setMode(e.target.value)}>{['問題優先','只看問題','可借車多','可還位多'].map(m=><option key={m}>{m}</option>)}</select></section><section className="grid"><Metric n={data.count} label="即時站點"/><Metric n={data.summary.problem} label="需注意站點"/><Metric n={data.summary.noBike} label="無車可借"/><Metric n={data.summary.noDock} label="無位可還"/></section><section className="card insight"><b>{data.cityName}狀態摘要：</b> 目前共有 {data.count.toLocaleString()} 站，{data.summary.problem.toLocaleString()} 站需要注意；無車 {data.summary.noBike} 站、無位 {data.summary.noDock} 站{data.summary.eBikes ? `，可借電輔車 ${data.summary.eBikes} 台` : ''}。</section>{city==='tainan'&&<section className="routes">{routeCards.map(route=><article className="route" key={route.id}><div><div className="name">{route.name}</div><div className="area">{route.theme}</div><p>{route.tip}</p></div><div className="routeStops">{route.stops.map(stop=><div className="stop" key={stop.name}><b>{stop.name}</b>{stop.stations.length?stop.stations.map(st=><span key={st.id} className={`mini ${st.level}`}>{st.name}｜借 {st.bikes} 還 {st.docks}</span>):<span className="mini warn">附近站點待人工確認</span>}</div>)}</div></article>)}</section>}<section className="stations">{stations.map(s=><article className="station" key={s.id}><div className="stationHead"><div><div className="name">{s.name}</div><div className="area">{s.area}｜{s.address}</div></div><span className={`pill ${s.level}`}>{s.label}</span></div><div className="bars"><div><div className="label">可借 {s.bikes} / {s.total}</div><div className="bar"><i style={{width:`${s.total?Math.round(s.bikes/s.total*100):0}%`}}/></div></div><div><div className="label">可還 {s.docks} / {s.total}</div><div className="bar"><i style={{width:`${s.total?Math.round(s.docks/s.total*100):0}%`}}/></div></div></div><div className="meta"><span>更新：{s.updatedAt}</span><span>ID：{s.id}</span></div></article>)}</section><p className="footer">資料來源：{data.cityName} YouBike 即時公開資料；每 60 秒自動重抓。Fetched: {new Date(data.fetchedAt).toLocaleString('zh-TW')}</p></>}
 </main>
}
function Metric({n,label}:{n:number;label:string}){return <div className="card"><div className="metric">{n.toLocaleString()}</div><div className="label">{label}</div></div>}
